---
# tasks file for router
- name: Generate Config Files
  ansible.builtin.debug:
    msg: Hello

- name: Create Conf Files
  template:
    src: router_template.j2
    dest: "./{{ item }}.txt"
  vars:
    hostname: "{{ item }}"
  loop:
    - "R1"
    - "R2"
    - "R3"
